---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# Load packages
```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(dplyr)
library(formattable)
library(countrycode)
library(maps)
```


2. # Clean up the data. 
```{r}
#Merge two datasets and mutate colomns
df1<- merge(X2016[,c(1,3,7,8,9)],
           X2017[,c(1,2,6,7,8)],
           by.x = "Country",
           by.y = "Country")
colnames(df1)<-c("Country","Happiness_Rank_2016","Happiness_Rank_2017","Economy_GDP_per_capita_2016","Economy_GDP_per_capita_2017","Family_2016","Family_2017","Health_2016","Health_2017")


Happiness_Rank_Difference<- function(x,y){
  x-y 
}
  df1 %>% 
  mutate(Happiness_Rank_Difference= Happiness_Rank_2017, Happiness_Rank_2016)  

Economics_Difference <-function(x,y){
  x-y
}
  df1 %>% 
  mutate(Economics_Difference=Economy_GDP_per_capita_2017-Economy_GDP_per_capita_2016)
  
Family_Difference <- function(x,y){
    x-y
  } 
df1 %>% 
  mutate(Family_Difference=Family_2017,Family_2016)

Health_Difference <- function(x,y){
  x-y
}
df1 %>% 
  mutate(Health_Difference=Health_2017,Health_2016)
  
df1
```

```{r}
#form a data table 
formattable(df1,list(
  `Rank Change` = formatter(
    "span",
    style=~formattable::style(color=ifelse(`Rank Change`>0,"green","red"))))) %>%
    as.datatable()
```

# Add one column for cotinents. Would like to see the correlation between continents and hapiness. 
```{r}
continent <- function(country){ 
  Europe <- c("Norway", "Denmark", "Iceland", "Switzerland", "Finland","Netherlands", "Sweden", "Austria", "Ireland", "Germany","Belgium", "Luxembourg", "United Kingdom", "Czech Republic","Malta", "France", "Spain", "Slovakia", "Poland", "Italy","Russia", "Lithuania", "Latvia", "Moldova", "Romania","Slovenia", "North Cyprus", "Cyprus", "Estonia", "Belarus","Serbia", "Hungary", "Croatia", "Kosovo", "Montenegro","Greece", "Portugal", "Bosnia and Herzegovina", "Macedonia","Bulgaria", "Albania", "Ukraine")
  Australia <- c("New Zealand", "Australia")
  Asia <- c("Israel", "United Arab Emirates", "Singapore", "Thailand", "Taiwan Province of China","Qatar", "Saudi Arabia", "Kuwait", "Bahrain", "Malaysia", "Uzbekistan", "Japan","South Korea", "Turkmenistan", "Kazakhstan", "Turkey", "Hong Kong S.A.R., China", "Philippines","Jordan", "China", "Pakistan", "Indonesia", "Azerbaijan", "Lebanon", "Vietnam","Tajikistan", "Bhutan", "Kyrgyzstan", "Nepal", "Mongolia", "Palestinian Territories","Iran", "Bangladesh", "Myanmar", "Iraq", "Sri Lanka", "Armenia", "India", "Georgia", "Cambodia", "Afghanistan", "Yemen", "Syria")
  North_America <- c("Canada", "Costa Rica", "United States", "Mexico",  
"Panama","Trinidad and Tobago", "El Salvador", "Belize", "Guatemala","Jamaica", "Nicaragua", "Dominican Republic", "Honduras","Haiti")
  South_America <- c("Chile", "Brazil", "Argentina", "Uruguay","Colombia", "Ecuador", "Bolivia", "Peru","Paraguay", "Venezuela")
  
  ctnt <- case_when(country %in% Europe ~ "Europe",
                    country %in% Australia ~ "Australia",
                    country %in% Asia ~ "Asia",
                    country %in% North_America ~ "North_America",
                    country %in% South_America ~ "South_America")
  ctnt
  
  
}
```

```{r}
continent("Canada")  #test the feature
```





